In [12]:
import numpy as np
from scipy.special import expit as sigmoid, logit
import matplotlib.pyplot as plt

In [2]:
x = np.ones(2)

In [6]:
sigmoid(500*(x-0.25))

array([1., 1.])

In [10]:
x = np.random.normal(loc=0.05, scale=0.025/2, size=(100))
x = x[x < 0.1]
x = x[x > 0]
x[x>0.05] = 0.1 - x[x>0.05]

In [14]:
plt.hist(x,5)

(array([ 2.,  6., 18., 27., 47.]),
 array([0.01013855, 0.01807827, 0.02601798, 0.0339577 , 0.04189742,
        0.04983713]),
 <a list of 5 Patch objects>)